import React from "react";
import * as Icon from "react-feather";

// export const items = [
//   { divider: false, label: "", value: "main-nav" },
//   { label: "Dashboard", value: "Dashboard", icon: <Icon.Home /> },
//   { label: "Directory", value: "Directory", icon: <Icon.Activity /> },
//   {
//     label: "Settings",
//     value: "Settings",
//     icon: <Icon.Settings />,
//     children: [
//       {
//         label: "Settings",
//         value: "Settings",
//         icon: <Icon.Settings />,
//       },
//     ],
//   },
// ];

export const menuItems = [
  {
    label: "Dashboard",
    isActive: true,
    icon: <Icon.Home />,
    url: "/dashboard",
    divider: false,
    isSub: false,
    subItems: [],
  },
  {
    label: "Directory",
    isActive: false,
    icon: <Icon.Activity />,
    url: "/directory",
    divider: false,
    isSub: false,
    subItems: [],
  },
  {
    label: "Settings",
    isActive: false,
    icon: <Icon.Settings />,
    url: "/settings",
    divider: true,
    isSub: false,
    subItems: [
      {
        label: "General Settings",
        isActive: false,
        url: "/settings",
        icon: <Icon.Settings />,
        subItems: [],
        isSub: true,
      },
      {
        label: "System Settings",
        isActive: false,
        url: "/system-settings",
        icon: <Icon.Settings />,
        subItems: [],
        isSub: true,
      },
      {
        label: "Admin Settings",
        isActive: false,
        url: "/admin-settings",
        icon: <Icon.Settings />,
        subItems: [],
        isSub: true,
      },
      {
        label: "Post Settings",
        isActive: false,
        url: "/post-settings",
        icon: <Icon.Settings />,
        subItems: [],
        isSub: true,
      },
      {
        label: "Registration Settings",
        isActive: false,
        url: "/registration-settings",
        icon: <Icon.Settings />,
        subItems: [],
        isSub: true,
      },
      {
        label: "Payment Settings",
        isActive: false,
        url: "/payment-settings",
        icon: <Icon.Settings />,
        subItems: [],
      },
      {
        label: "Email Notification Settings",
        isActive: false,
        url: "/notification-settings",
        icon: <Icon.Settings />,
        subItems: [],
      },
      {
        label: "Security Settings",
        isActive: false,
        url: "/security-settings",
        icon: <Icon.Settings />,
        subItems: [],
      },
      {
        label: "Upload Settings",
        isActive: false,
        url: "/upload-settings",
        icon: <Icon.Settings />,
        subItems: [],
      },
    ],
  },
  {
    label: "User",
    isActive: false,
    icon: <Icon.User />,
    url: "/list-user",
    divider: false,
    subItems: [
      {
        label: "List Users",
        isActive: false,
        url: "/list-users",
        icon: <Icon.User />,
        subItems: [],
      },
      {
        label: "List Groups",
        isActive: false,
        url: "/list-group",
        icon: <Icon.User />,
        subItems: [],
      },
      {
        label: "List Pages",
        isActive: false,
        url: "/list-page",
        icon: <Icon.User />,
        subItems: [],
      },
      {
        label: "List Agency",
        isActive: false,
        url: "/list-agency",
        icon: <Icon.User />,
        subItems: [],
      },
      {
        label: "List Admin",
        isActive: false,
        url: "/list-admin",
        icon: <Icon.User />,
        subItems: [],
      },
      {
        label: "List Online",
        isActive: false,
        url: "/list-online",
        icon: <Icon.User />,
        subItems: [],
      },
      {
        label: "List Banned",
        isActive: false,
        url: "/list-banned",
        icon: <Icon.User />,
        subItems: [],
      },
    ],
  },
  {
    label: "Posts",
    isActive: false,
    icon: <Icon.MessageSquare />,
    url: "/posts ",
    divider: false,
    subItems: [],
  },
  {
    label: "Events",
    isActive: false,
    icon: <Icon.Calendar />,
    url: "/event",
    divider: true,
    subItems: [
      {
        label: "List Event",
        isActive: false,
        url: "/event",
        icon: <Icon.Calendar />,
        subItems: [],
      },
      {
        label: "Event Category",
        isActive: false,
        url: "/event-category",
        icon: <Icon.Calendar />,
        subItems: [],
      },
    ],
  },
  {
    label: "Ads",
    isActive: false,
    icon: <Icon.DollarSign />,
    url: "/ads-settings",
    divider: false,
    subItems: [
      {
        label: "Ad Settings",
        isActive: false,
        url: "/ads-settings",
        icon: <Icon.DollarSign />,
        subItems: [],
      },
      {
        label: "System Ads",
        isActive: false,
        url: "/system-ads",
        icon: <Icon.DollarSign />,
        subItems: [],
      },
      {
        label: "User Ads",
        isActive: false,
        url: "/user-ads",
        icon: <Icon.DollarSign />,
        subItems: [],
      },
    ],
  },
  {
    label: "Content on Demand",
    isActive: false,
    icon: <Icon.Package />,
    url: "/cod-settings",
    divider: false,
    subItems: [
      {
        label: "CoD Settins",
        isActive: false,
        url: "/cod-settings",
        icon: <Icon.Package />,
        subItems: [],
      },
      {
        label: "User CoD",
        isActive: false,
        url: "/user-cod",
        icon: <Icon.Package />,
        subItems: [],
      },
      {
        label: "Cod Earnings",
        isActive: false,
        url: "/cod-earnings",
        icon: <Icon.Package />,
        subItems: [],
      },
    ],
  },
  {
    label: "Pro Packages",
    isActive: false,
    icon: <Icon.Briefcase />,
    url: "/package",
    divider: false,
    subItems: [
      {
        label: "Settings",
        isActive: false,
        url: "/package",
        icon: <Icon.Briefcase />,
        subItems: [],
      },
      {
        label: "List Subscribers",
        isActive: false,
        url: "/subscribers",
        icon: <Icon.Briefcase />,
        subItems: [],
      },
      {
        label: "Earnings",
        isActive: false,
        url: "/earnings",
        icon: <Icon.Briefcase />,
        subItems: [],
      },
    ],
  },
  {
    label: "Qubes",
    isActive: false,
    icon: <Icon.Codepen />,
    url: "/qubes",
    divider: true,
    subItems: [
      {
        label: "Points",
        isActive: false,
        url: "/qubes",
        icon: <Icon.Codepen />,
        subItems: [],
      },
      {
        label: "Payments",
        isActive: false,
        url: "/qube-payments",
        icon: <Icon.Codepen />,
        subItems: [],
      },
    ],
  },
  {
    label: "Reports",
    isActive: false,
    icon: <Icon.FileText />,
    url: "/reports",
    divider: false,
    subItems: [],
  },
  {
    label: "Verification",
    isActive: false,
    icon: <Icon.Key />,
    url: "/verification",
    divider: false,
    subItems: [],
  },
  {
    label: "Follow Suggest",
    isActive: false,
    icon: <Icon.Link />,
    url: "/follow-suggest",
    divider: false,
    subItems: [],
  },
  {
    label: "Gabbage Collector",
    isActive: false,
    icon: <Icon.Archive />,
    url: "/gabbage",
    divider: false,
    subItems: [],
  },
  {
    label: "Mass Notification",
    isActive: false,
    icon: <Icon.Volume2 />,
    url: "/notification",
    divider: true,
    subItems: [],
  },
  {
    label: "Emojis",
    isActive: false,
    icon: <Icon.Smile />,
    url: "/emojis",
    divider: false,
    subItems: [],
  },
  {
    label: "Reactions",
    isActive: false,
    icon: <Icon.Target />,
    url: "/reactions",
    divider: true,
    subItems: [],
  },
  {
    label: "Aggregate Data",
    isActive: false,
    icon: <Icon.Database />,
    url: "/data",
    divider: false,
    subItems: [],
  },
];
